name: upcp
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - ipympl
  - ipywidgets
  - jupyterlab
  - folium>=0.12
  - matplotlib>=3.4
  - numba>=0.54
  - numpy>=1.20
  - owslib>=0.27
  - pandas>=1.3
  - pyntcloud>=0.3.1
  - shapely>=1.8
  - scikit-learn>=0.24
  - scipy>=1.6
  - tifffile>=2021.6
  - tqdm>=4.60
  - zarr>=2.8
  - pip:
    - laspy[lazrs]~=2.0
    - open3d~=0.16.0
